'use client';

import { GlobalStyle } from '@/styles/GlobalStyle';
import light from '@/styles/themes/light';
import { ThemeProvider } from 'styled-components';

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <ThemeProvider theme={light}>
      <html lang='pt-br'>
        <GlobalStyle />

        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}
