'use client';

import { useState } from 'react';

import { Header } from '@/components/Header';

import { GlobalStyle } from '@/styles/GlobalStyle';
import light from '@/styles/themes/light';
import dark from '@/styles/themes/dark';
import { ThemeProvider, DefaultTheme } from 'styled-components';

import { Plus_Jakarta_Sans } from 'next/font/google';

const jakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  const [theme, setTheme] = useState<DefaultTheme>(dark);

  function toggleTheme() {
    setTheme(theme.title === 'light' ? dark : light);
  }

  return (
    <ThemeProvider theme={theme}>
      <html lang='pt-br'>
        <GlobalStyle />

        <body
          className={jakartaSans.className}
          suppressHydrationWarning={true}
        >
          <Header
            toggleTheme={toggleTheme}
            theme={theme}
          />

          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
